### PR TITLE
Fix to support PHP 8.1

### PR DESCRIPTION
**Pull request by dan-tang-ssd**
PR #1 is working fine with PHP 8.0, all 3 test cases passed.

When I use PHP 8.1, all 3 test cases failed with different error.

This PR aims to fix these errors and make this package compatiable with PHP 8.1.

### CODE REVIEW

**Comment by dan-tang-ssd** [comment]
Test case 1, Tag CRUD panel, add tag

BEFORE fix:
image

After fix:
It works well now

**Comment by dan-tang-ssd** [comment]
Test case 2, CRUD panel, Export tags

image

**Comment by dan-tang-ssd** [comment]
Test case 3, CRUD panel, Import tags

image

**Comment by dan-tang-ssd** [comment]
For test case 2 and 3, suspects Laravel Excel package "maatwebsite/excel" not yet support PHP 8.1.

We are currently using Laravel Excel v3.1.33.
Checked that Laravel Excel support PHP 8.1 since v3.1.34. Latest version is v3.1.40.
[https://github.com/SpartnerNL/Laravel-Excel/releases/tag/3.1.34](url)

with PHP 8.1, failed to upgrade to due to:
- nette/schema v1.2.1 requires php >=7.1 <8.1 -> your php version (8.1.8) does not satisfy that requirement.

with PHP 8.0, upgraded from v3.1.33 to v3.1.40 successfully

Perform testing with PHP 8.0, all 3 test cases success.
Perform testing with PHP 8.1, add tag success, but export and import still failed with error message same as v3.1.33.

**Comment by dave-mills** [comment]
The other PR here might be of benefit. I updated the dependencies to Laravel 9, and in doing so removed the Laravel Excel requirement - see #2 for details and reasoning. (Main reasoning is to try and have as few dependencies as possible; so we let the user install Laravel Excel if they want to use the import/export features).

So - with the json_decode() depreciation fix, does the Laravel 9 branch work in PHP 8.1?

**Comment by dan-tang-ssd** [comment]
> The other PR here might be of benefit. I updated the dependencies to Laravel 9, and in doing so removed the Laravel Excel requirement - see #2 for details and reasoning. (Main reasoning is to try and have as few dependencies as possible; so we let the user install Laravel Excel if they want to use the import/export features).

Yes, that's good.


> So - with the json_decode() depreciation fix, does the Laravel 9 branch work in PHP 8.1?

I have applied a minor fix to make it work properly in PHP 8.1.

**Comment by dan-tang-ssd** [comment]
I think this PR is no longer necessary, I will close it now.

**Pull request closed without merging**
